#!/usr/bin/env python3
"""Auto-geocode README locations that are missing from geocode.py's GEO table.

Pipeline position:  parse_readme.py -> autofill_geo.py -> geocode.py

For every location in tools/raw_attacks.json with no entry in the GEO dict
(imports it from geocode.py), this script:

  1. Queries Nominatim (OpenStreetMap) — full location string first, then
     progressively drops trailing qualifiers when a query returns nothing
     (e.g. "Mont-sur-Lausanne, France" only resolves without the country).
  2. Prefers results whose name actually contains the queried toponym.
  3. Verifies the resolved point falls inside the returned country's polygon
     (Natural Earth 10m, same source audit_coords.py uses) — guards against
     swapped lat/lng and wrong-place matches like Paris, TX -> Paris, FR.
  4. Appends verified entries to the GEO dict in geocode.py under an
     auto-generated section, so future runs reuse them (Nominatim-friendly).

Country disagreements between the README suffix and Nominatim are kept from
the geocoder (polygon-verified truth) and reported loudly — that pattern
usually means the README row itself is wrong. Locations that cannot be
resolved or verified are listed and the script exits 1 (fail closed).
"""
import json
import sys
import time
import urllib.parse
import urllib.request
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
sys.path.insert(0, str(TOOLS))

import geocode                      # gives us the current GEO dict
from audit_coords import WORLD, ISO2_TO_3, point_in_geometry

RAW = TOOLS / "raw_attacks.json"
GEOCODE = TOOLS / "geocode.py"

NOMINATIM = "https://nominatim.openstreetmap.org/search"
UA = {"User-Agent": "physical-bitcoin-attacks-autofill/1.0 (+https://github.com; CI pipeline)"}
PAUSE = 1.1  # seconds between Nominatim requests (usage policy: <= 1 req/s)

SECTION_HEADER = "    # ---- Auto-generated by tools/autofill_geo.py (Nominatim) ----"

# Country tokens that appear at the end of README location strings but never
# as the "country" field of a GEO value (e.g. GB entries say "United Kingdom").
COUNTRY_ALIASES = {
    "england": "GB", "scotland": "GB", "wales": "GB",
    "northern ireland": "GB", "uk": "GB", "u.k.": "GB",
    "usa": "US", "u.s.": "US", "u.s.a.": "US",
    "uae": "AE", "south korea": "KR", "vietnam": "VN",
}


def nominatim(query):
    params = {"q": query, "format": "jsonv2", "addressdetails": "1", "limit": "5"}
    url = NOMINATIM + "?" + urllib.parse.urlencode(params)
    req = urllib.request.Request(url, headers=UA)
    with urllib.request.urlopen(req, timeout=15) as resp:
        return json.load(resp)


def pick(results, primary):
    """Prefer a result whose toponym actually contains what we asked for."""
    primary = primary.lower()
    for r in results:
        haystack = ((r.get("name") or "") + " " + (r.get("display_name") or "")).lower()
        if primary in haystack:
            return r
    return results[0] if results else None


def resolve(location):
    """Try the full string, then progressively shorter prefixes of it."""
    parts = [p.strip() for p in location.split(",") if p.strip()]
    queries = [", ".join(parts[:i]) for i in range(len(parts), 0, -1)]
    for query in queries:
        results = nominatim(query)
        time.sleep(PAUSE)
        hit = pick(results, parts[0])
        if hit:
            return hit
    return None


def entry_from_hit(location, hit):
    addr = hit.get("address") or {}
    city = (addr.get("city") or addr.get("town") or addr.get("village")
            or addr.get("municipality") or hit.get("name") or "")
    region = addr.get("state") or ""
    country = addr.get("country") or ""
    iso2 = (addr.get("country_code") or "").upper()
    lat = round(float(hit["lat"]), 2)
    lng = round(float(hit["lon"]), 2)
    return (city, region, country, iso2, lat, lng)


def expected_iso2(location):
    last = location.split(",")[-1].strip().lower()
    if last in COUNTRY_ALIASES:
        return COUNTRY_ALIASES[last]
    for v in geocode.GEO.values():
        if v[2].lower() == last:
            return v[3]
    return None


def load_world_geoms():
    """Return ({ISO2: geometry}, {ISO3: geometry}) from NE admin-0 polygons."""
    print(f"downloading country polygons from {WORLD} ...", flush=True)
    req = urllib.request.Request(WORLD, headers=UA)
    with urllib.request.urlopen(req, timeout=60) as resp:
        world = json.load(resp)
    geoms = {}
    for f in world["features"]:
        p = f["properties"]
        a2 = (p.get("ISO_A2_EH") or p.get("ISO_A2") or "").upper()
        a3 = (p.get("ADM0_A3") or "").upper()
        # NE uses "-99" for missing codes (e.g. France/Kosovo quirks); skip those
        if a2 and a2 != "-99":
            geoms.setdefault(a2, f["geometry"])
        if a3 and a3 != "-99":
            geoms.setdefault(a3, f["geometry"])
    return geoms


def append_to_geocode_py(entries):
    """Insert new GEO entries just before the dict's closing brace."""
    text = GEOCODE.read_text(encoding="utf-8")
    dict_start = text.index("GEO = {")
    dict_end = text.index("\n}", dict_start)
    # make sure the line before the closing brace ends with a comma
    if text[:dict_end].rstrip().endswith(('"', ")")) and not text[:dict_end].rstrip().endswith(","):
        text = text[:dict_end].rstrip() + "," + text[dict_end:]
        dict_end = text.index("\n}", dict_start)
    lines = ["", SECTION_HEADER]
    for loc, (city, region, country, iso2, lat, lng) in sorted(entries.items()):
        line = (f"    {loc!r}: ({city!r}, {region!r}, {country!r}, "
                f"{iso2!r}, {lat}, {lng}),")
        lines.append(line)
    text = text[:dict_end] + "\n".join(lines) + text[dict_end:]
    GEOCODE.write_text(text, encoding="utf-8")


def main():
    attacks = json.loads(RAW.read_text(encoding="utf-8"))
    missing = sorted({a["location"] for a in attacks
                      if a.get("location") and a["location"] not in geocode.GEO})
    if not missing:
        print("autofill: all locations already present in GEO")
        return

    print(f"autofill: {len(missing)} location(s) missing from GEO:")
    for m in missing:
        print(f"  {m}")

    geoms = load_world_geoms()
    new_entries, failures, warnings = {}, [], []

    for loc in missing:
        hit = resolve(loc)
        if hit is None:
            failures.append(f"{loc}: no Nominatim result")
            continue
        entry = entry_from_hit(loc, hit)
        city, region, country, iso2, lat, lng = entry
        if not iso2 or not country:
            failures.append(f"{loc}: result missing country info ({hit.get('display_name')})")
            continue

        # Resolve polygon: ISO2/ISO3 both live in one map (NE carries both).
        geom = geoms.get(iso2) or geoms.get(ISO2_TO_3.get(iso2))
        if geom is None or not point_in_geometry(lat, lng, geom):
            failures.append(f"{loc}: point ({lat}, {lng}) not inside {country} polygon")
            continue

        expected = expected_iso2(loc)
        if expected and expected != iso2:
            warnings.append(
                f"{loc}: README says country '{loc.split(',')[-1].strip()}' "
                f"but Nominatim resolved it to {country} ({iso2}) — "
                f"using the verified geocoder result; check the README row")
        print(f"  + {loc!r} -> ({city!r}, {region!r}, {country!r}, {iso2!r}, {lat}, {lng})")
        new_entries[loc] = entry

    if new_entries:
        append_to_geocode_py(new_entries)
        print(f"autofill: appended {len(new_entries)} entr"
              f"{'y' if len(new_entries) == 1 else 'ies'} to {GEOCODE.name}")

    for w in warnings:
        print(f"WARNING: {w}")
    if failures:
        print("\nFAILED to auto-geocode:")
        for f in failures:
            print(f"  {f}")
        print("\nFix these README rows (or add manual GEO entries in geocode.py), then re-run.")
        raise SystemExit(1)


if __name__ == "__main__":
    main()
